# Generated by Django 4.2.9 on 2024-01-25 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=512)),
                ('arrive_time', models.DateTimeField()),
                ('current_passengers_num', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(blank=True, max_length=128)),
                ('special_request', models.TextField(blank=True)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('COMPLETE', 'Complete')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_rides', to='users.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ridesharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_arrive_date', models.DateTimeField()),
                ('latest_arrive_date', models.DateTimeField()),
                ('passenger_num', models.PositiveIntegerField(default=1)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharers', to='rides.ride')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
