# Generated by Django 4.2.9 on 2024-02-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETE', 'Complete')], default='OPEN', max_length=10),
        ),
    ]
