# Generated by Django 4.2.9 on 2024-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharer',
            name='special_request',
            field=models.TextField(blank=True),
        ),
    ]
